name: Build Kernel
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: morosakubek2/kernel_build_action@main
      with:
          kernel-url: https://github.com/morosakubek2/android_kernel_samsung_b2q
          kernel-dir: main
          branch: main
          config: b2q_eur_openx_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 14
          aosp-clang-version: r510928
          python-27: false
          disable-lto: false
          anykernel3: true
          ccache: false
          apatch: false
