# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: morosakubek2/kernel_build_action@main
      with:
          kernel-url: https://github.com/morosakubek2/android_kernel_samsung_sm8350_flip3
          kernel-branch: flip3
          config: vendor/b2q_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          other-clang-url: false
          other-clang-branch: false
          ksu: true
          ksu-version: main
          disable-lto: true
          anykernel3: true
          ccache: true
          apatch: false
